AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This is aws cloud formation template
Parameters:
  ImageId: 
    Description: Amazon image id
    Default: ami-02e136e904f3da870
    Type: String
  VpcId: 
    Type: String
Resources:
  Webserver:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo su
          yum update -y # good practice to update existing packages
          yum install -y httpd # install web server 
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World" > /var/www/html/index.html
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "open port 80"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
Outputs:
  PublicIp:
    Value: !GetAtt Webserver.PublicIp